---
- name: Define apache_packages
  set_fact:
    apache_packages: "{{ __apache_packages | list }}"
  when: apache_packages is not defined

- name: Define apache_server_root
  set_fact:
    apache_server_root: "{{ __apache_server_root }}"
  when: apache_server_root is not defined

- name: Define apache_default_vhost_name
  set_fact:
    apache_default_vhost_name: "{{ __apache_default_vhost_name }}"
  when: apache_default_vhost_name is not defined

- name: Define apache_service
  set_fact:
    apache_service: "{{ __apache_service }}"
  when: apache_service is not defined

- name: Define apache_conf_path
  set_fact:
    apache_conf_path: "{{ __apache_conf_path }}"
  when: apache_conf_path is not defined

- name: Define apache_port_conf_file
  set_fact:
    apache_port_conf_file: "{{ __apache_port_conf_file }}"
  when: apache_port_conf_file is not defined

- name: Define apache_ports_configuration_items
  set_fact:
    apache_ports_configuration_items: "{{ __apache_ports_configuration_items }}"
  when: apache_ports_configuration_items is not defined
